# https://dart.dev/get-dart

- block:
  - name: install Apt key
    ansible.builtin.shell: wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/dart.gpg
    args:
      creates: /usr/share/keyrings/dart.gpg

  - name: Repo
    ansible.builtin.apt_repository:
      repo: "deb [signed-by=/usr/share/keyrings/dart.gpg arch=amd64] https://storage.googleapis.com/download.dartlang.org/linux/debian stable main"
      state: present

  - name: install Dart
    ansible.builtin.apt:
      pkg:
      - dart
  when: ubuntu_default not in common
  become: true


- include_tasks: "common/{{ubuntu_default}}/main.yml"
  when: ubuntu_default in common